[project]
name = "snake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datastar-py>=0.6.5",
    "fastapi>=0.119.0",
    "rich>=14.2.0",
    "uvicorn>=0.38.0",
]
